name: Compile Pawn

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Pawn Compiler
      run: |
        wget https://github.com/pawn-lang/compiler/releases/download/v3.10.9/pawncc-linux.zip
        unzip pawncc-linux.zip
        chmod +x pawncc
        ./pawncc -v

    - name: Compile new.pwn
      run: |
        ./pawncc new.pwn
      working-directory: ./  # sesuaikan kalau file di folder tertentu

    - name: Upload compiled amx
      uses: actions/upload-artifact@v3
      with:
        name: new-amx
        path: new.amx
